---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICENAME
  namespace: NAMESPACE
spec:
  selector:
    matchLabels:
      app: SERVICENAME
  replicas: 1
  template:
    metadata:
      labels:
        app: SERVICENAME
        group: api
    spec:
      hostname: SERVICENAME
      containers:
      - name: SERVICENAME
        image: BASEIMAGE/SERVICENAME:TAG
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: endpoint-configmap
        ports:
        - name: http
          containerPort: PORT
        resources:
          limits:
            cpu: "0.3"
            memory: "600Mi"
          requests:
            cpu: "0.2"
            memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME
  namespace: NAMESPACE
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: SERVICENAME
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: SERVICENAME-ingress
  namespace: NAMESPACE
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # http://SERVICENAME.localtest.me/
  - host: SERVICENAME.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: SERVICENAME
            port:
              number: 80