apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: local
  source:
    path: library
    repoURL: https://github.com/amitkshirsagar13/apps.git
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true