apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-stack
  namespace: argocd
spec:
  project: local
  source:
    path: library/local
    repoURL: https://github.com/amitkshirsagar13/apps.git
    targetRevision: HEAD
  destination:
    namespace: local
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true