apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local
  namespace: tooling
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Kubernetes Cluster

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/amitkshirsagar13/apps.git'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: tooling
    server: https://kubernetes.default.svc
  - namespace: apps
    server: https://kubernetes.default.svc
  - namespace: gloo-system
    server: https://kubernetes.default.svc
  - namespace: storage
    server: https://kubernetes.default.svc
  - namespace: local
    server: https://kubernetes.default.svc
    
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'