---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
  namespace: local
spec:
  selector:
    matchLabels:
      app: sample-service
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-service
        group: api
    spec:
      hostname: sample-service
      containers:
      - name: sample-service
        image: amitkshirsagar13/sample-service:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: endpoint-configmap
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: "0.3"
            memory: "600Mi"
          requests:
            cpu: "0.2"
            memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: local
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: sample-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-service-ingress
  namespace: local
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # http://sample-service.localtest.me/
  - host: sample-service.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-service
            port:
              number: 80