apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: local
  source:
    path: helm
    repoURL: https://github.com/amitkshirsagar13/sample-service.git
    targetRevision: HEAD
    helm:
      version: v3
      values: |
        image:
          tag: latest
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true