apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-app
  namespace: argocd
spec:
  project: local
  source:
    repoURL: https://github.com/amitkshirsagar13/apps.git
    targetRevision: HEAD
    path: library/local/gloo-envoy
  destination: 
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
