apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtual-services
  namespace: tooling
spec:
  project: local
  source:
    repoURL: https://github.com/amitkshirsagar13/apps.git
    targetRevision: HEAD
    path: gloo/base-services
  destination: 
    server: https://kubernetes.default.svc
    namespace: local
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
